# Generated by Django 3.1.1 on 2020-10-11 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201011_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 14, 51, 32, 594739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof',
            field=models.ImageField(default='default/default-profile.png', upload_to=''),
        ),
    ]
