# Generated by Django 3.1.1 on 2020-10-11 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201011_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 14, 52, 35, 689087, tzinfo=utc)),
        ),
    ]
