# Generated by Django 3.1.1 on 2020-10-11 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201011_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 14, 57, 17, 126407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof',
            field=models.ImageField(default='images/default/default-profile.png', upload_to=''),
        ),
    ]
