# Generated by Django 3.1.1 on 2020-10-11 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201011_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 15, 1, 36, 501946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof',
            field=models.ImageField(default='images\\default\\defaul-profile.png', upload_to=''),
        ),
    ]
