# Generated by Django 3.1.1 on 2020-10-12 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20201012_1146'),
        ('member', '0002_auto_20201012_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(to='books.Book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 9, 49, 42, 92496, tzinfo=utc)),
        ),
    ]
