# Generated by Django 3.1.1 on 2020-10-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20201020_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='return_date',
        ),
    ]
